server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/820627765/microservicecloud-config.git  # 配置github上面的git仓库地址