server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  # eureka 服务端实例的名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false 表示自己就就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群环境需要配置多个 eureka 的服务端的访问地址，多个用逗号分隔
      defaultZone : http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 设置与 erureka server 交互的地址，查询服务和注册服务都要依赖这个地址。就是对外暴露的eureka 的服务地址